formatter: markdown

header-from: docs/HEADER.md

sections:
  hide: []
  show:
  - header
  - providers
  - inputs
  - outputs

content: |-
  {{ .Header }}
  {{ .Providers }}
  {{ .Inputs }}
  {{ .Outputs }}


output:
  file: README.md
  mode: replace
  template: "<!-- BEGIN_TF_DOCS -->\n{{ .Content }}\n<!-- END_TF_DOCS --> \n"

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 4
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
